name: Deploy
on: workflow_call
jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # https://github.com/docker/login-action#github-container-registry
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/docker/setup-buildx-action#usage
      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      # https://github.com/docker/build-push-action#usage
      - uses: docker/build-push-action@ee4ca427a2f43b6a16632044ca514c076267da23 # v6.19.0
        with:
          push: true
          file: Dockerfile_django
          tags: |
            ghcr.io/${{ github.repository }}-django:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: docker/build-push-action@ee4ca427a2f43b6a16632044ca514c076267da23 # v6.19.0
        with:
          push: true
          file: Dockerfile_static
          tags: |
            ghcr.io/${{ github.repository }}-static:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
